// vue-remote/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: vue-remote</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
    <Counter />
  </div>
</template>

<script>
import Counter from './Counter.vue'

export default {
  components: {
    Counter
  }
}
</script>

// host/src/App.jsx
import React from "react";
import ReactDOM from "react-dom/client";
import Counter from "remote/Counter";

import "./index.scss";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: host</div>
    <div>Framework: react</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
    <Counter />
  </div>
);
const rootElement = document.getElementById("app")
if (!rootElement) throw new Error("Failed to find the root element")

const root = ReactDOM.createRoot(rootElement)

root.render(<App />)
